# Generated by Django 4.0 on 2021-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_is_active',
            field=models.BooleanField(default=False, verbose_name='Is server active'),
        ),
    ]
