# Generated by Django 4.0 on 2021-12-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbr_srv_side', '0003_perfmonlog_alter_server_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfmonlog',
            options={'verbose_name': 'Performance Monitor Log'},
        ),
        migrations.AlterField(
            model_name='cpuinformation',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_information', to='rbr_srv_side.perfmonlog'),
        ),
        migrations.AlterField(
            model_name='diskinformation',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_information', to='rbr_srv_side.perfmonlog'),
        ),
        migrations.AlterField(
            model_name='hostinformation',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_information', to='rbr_srv_side.perfmonlog'),
        ),
        migrations.AlterField(
            model_name='loadaverage',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_average', to='rbr_srv_side.perfmonlog'),
        ),
        migrations.AlterField(
            model_name='memoryinformation',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_information', to='rbr_srv_side.perfmonlog'),
        ),
        migrations.AlterField(
            model_name='networkinformation',
            name='perf_mon_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_information', to='rbr_srv_side.perfmonlog'),
        ),
    ]
